package com.example.demo.serviceimpl;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import com.example.demo.dto.NotificationsDTO;
import com.example.demo.dto.RequiredResponseDTO;
import com.example.demo.dto.UsersDTO;
import com.example.demo.entity.Notifications;
import com.example.demo.exceptions.InvalidNotificationException;
import com.example.demo.exceptions.NotificationNotFoundException;
import com.example.demo.exceptions.NotificationServiceException;
import com.example.demo.repository.NotificationsRepository;
import com.example.demo.service.NotificationsService;

@Service
public class NotificationsServiceImpl implements NotificationsService {

    @Autowired
    private NotificationsRepository notificationRepo;

    @Autowired
    private RestTemplate restTemplate;

    @Override
    public NotificationsDTO createNotification(NotificationsDTO dto) {
        if (dto == null) {
            throw new InvalidNotificationException("Notification payload must not be null.");
        }
        if (dto.getUserID() == null) {
            throw new InvalidNotificationException("Notification userID is required.");
        }
        if (dto.getMessage() == null || dto.getMessage().trim().isEmpty()) {
            throw new InvalidNotificationException("Notification message is required.");
        }
        if (dto.getCategory() == null || dto.getCategory().trim().isEmpty()) {
            throw new InvalidNotificationException("Notification category is required.");
        }

        Notifications n = new Notifications();
        n.setUserID(dto.getUserID());
        n.setMessage(dto.getMessage());
        n.setCategory(dto.getCategory());
        n.setStatus(dto.getStatus() != null ? dto.getStatus() : "UNREAD");
        n.setCreatedAt(dto.getCreatedAt() != null ? dto.getCreatedAt() : LocalDateTime.now());
        n.setEntityID(dto.getEntityID());

        try {
            Notifications saved = notificationRepo.save(n);
            // Return the fully populated DTO including timestamp generated by DB/service
            return convertToDto(saved);
        } catch (Exception ex) {
            throw new NotificationServiceException("Unable to save notification: " + ex.getMessage(), ex);
        }
    }

    @Override
    public RequiredResponseDTO getAllDataByUserId(Long userId) {
        if (userId == null) {
            throw new InvalidNotificationException("userId is required.");
        }

        RequiredResponseDTO response = new RequiredResponseDTO();

        try {
            UsersDTO user = restTemplate.getForObject("http://localhost:8082/auth/user/" + userId, UsersDTO.class);
            response.setUser(user);
        } catch (Exception ex) {
            throw new NotificationServiceException("Unable to fetch user details from Identity Service: " + ex.getMessage(), ex);
        }

        List<Notifications> notifications = notificationRepo.findByUserID(userId);

        if (notifications == null || notifications.isEmpty()) {
            throw new NotificationNotFoundException("No notifications found for userId: " + userId);
        }

        List<NotificationsDTO> dtoList = notifications.stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());

        response.setNotifications(dtoList);
        return response;
    }

    @Override
    public List<NotificationsDTO> getNotificationsByUserId(Long userID) {
        // Return only the list of DTOs (if required by other internal logic)
        return notificationRepo.findByUserID(userID).stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }
    
    /**
     * Helper method to handle Entity-to-DTO conversion consistently
     */
    private NotificationsDTO convertToDto(Notifications n) {
        NotificationsDTO d = new NotificationsDTO();
        d.setNotificationID(n.getNotificationID());
        d.setUserID(n.getUserID());
        d.setEntityID(n.getEntityID());
        d.setMessage(n.getMessage());
        d.setCategory(n.getCategory());
        d.setStatus(n.getStatus());
        d.setCreatedAt(n.getCreatedAt());
        return d;
    }
}